class_name Loc
extends RefCounted
## NEFES yerelleştirme çekirdeği (S3/H1): Loc.t(anahtar) → aktif dilde metin.
## Kapsam: menü/bar/panel yüzeyi + isimler + olay akışı (ev_*). Mektup havuzları Letters'ta (tek kaynak).
## Dil Settings("lang")'de; ilk açılışta OS dilinden tahmin. Değişim ui.rebuild ile anında.

static var lang := "tr"

static func boot() -> void:
	var d := Settings.get_str("lang", "")
	if d == "":
		d = "tr" if OS.get_locale_language() == "tr" else "en"
	lang = d

static func set_lang(l: String) -> void:
	lang = "tr" if l == "tr" else "en"
	Settings.set_str("lang", lang)

static func t(k: String) -> String:
	var e: Dictionary = T.get(k, {})
	return e.get(lang, e.get("tr", k))

const T := {
	"identity": { "tr": "ekranının altında, sen çalışırken uyanan minyatür bir kasaba", "en": "a miniature town at the bottom of your screen, waking as you work" },
	"resume": { "tr": "▶  Devam Et", "en": "▶  Resume" },
	"new_town": { "tr": "🌱 Yeni Kasaba", "en": "🌱 New Town" },
	"credits": { "tr": "ℹ Krediler", "en": "ℹ Credits" },
	"quit": { "tr": "✕ Kaydet ve Çık", "en": "✕ Save & Quit" },
	"confirm_new": { "tr": "Emin misin? Mevcut kasaban güvenle yedeklenecek (save.json.bak) ve bugünün tohumuyla yepyeni bir kasaba uyanacak. Bir daha dokunursan başlıyoruz.", "en": "Are you sure? Your current town will be safely backed up (save.json.bak) and a brand-new town will wake with today's seed. Tap again to begin." },
	"credits_body": { "tr": "NEFES — Rain City evreni.\nGodot Engine ile yapıldı (MIT lisansı, © Godot Engine katkıcıları).\nTüm görseller prosedürel, tüm sesler %100 sentez.\nSolo geliştirici + Claude.", "en": "NEFES — the Rain City universe.\nMade with Godot Engine (MIT license, © Godot Engine contributors).\nAll visuals procedural, all audio 100% synthesized.\nSolo developer + Claude." },
	"settings": { "tr": "⚙  AYARLAR", "en": "⚙  SETTINGS" },
	"scale": { "tr": "pencere ölçeği", "en": "window scale" },
	"fit": { "tr": "⛶ sığdır", "en": "⛶ fit" },
	"vertical": { "tr": "↕ dikey/yatay", "en": "↕ vertical/horizontal" },
	"language": { "tr": "dil / language", "en": "language / dil" },
	"quick": { "tr": "açılışta menüyü atla, doğrudan kasabaya gel", "en": "skip this menu on launch, go straight to town" },
	"framed": { "tr": "🪟 çerçeveli pencere (taşı/boyutlandır — yeniden başlatınca tam etki)", "en": "🪟 framed window (move/resize — full effect on restart)" },
	"demo_title": { "tr": "🌙 DEMO BURADA BİTİYOR", "en": "🌙 THE DEMO ENDS HERE" },
	"demo_body": { "tr": "Kasabanın ilk 7 günü seninleydi — teşekkür ederiz. Sakinlerin, mektupların ve melodin güvenle kaydedildi; tam sürümde kasaban kaldığı yerden büyümeye devam edecek. Işıklar hep yanık kalsın. 💛",
		"en": "The town's first 7 days were yours — thank you. Your residents, letters and melody are safely saved; in the full game your town will keep growing right where it left off. May the lights stay warm. 💛" },
	"powersave": { "tr": "🔋 pil dostu mod (20fps)", "en": "🔋 battery saver (20fps)" },
	"dev_speed": { "tr": "⏩ dev hız", "en": "⏩ dev speed" },
	"hint": { "tr": "Esc: menü/panel kapat · V: dikey · pencereyi boş alandan sürükle", "en": "Esc: menu/close panel · V: vertical · drag window from empty space" },
	"start": { "tr": "🎯 Başlat", "en": "🎯 Start" },
	"leave": { "tr": "bırak", "en": "stop" },
	"break_skip": { "tr": "☕ %02d:%02d ▶", "en": "☕ %02d:%02d ▶" },
	"tt_break": { "tr": "Mola — tıkla: molayı atla, yeni seans başlat", "en": "Break — click to skip and start a new session" },
	"replied_sep": { "tr": "— yanıtladıkların —", "en": "— replied —" },
	"work_fmt": { "tr": "🎯 %02d:%02d · bırak", "en": "🎯 %02d:%02d · stop" },
	"series": { "tr": "seri %d", "en": "streak %d" },
	"letters_btn": { "tr": "✉ Mektuplar %d", "en": "✉ Letters %d" },
	"letters_btn_s": { "tr": "✉ %d", "en": "✉ %d" },
	"town_menu": { "tr": "☰ Kasaba", "en": "☰ Town" },
	"snd_row": { "tr": "🔊 Ses atmosferi", "en": "🔊 Sound atmosphere" },
	"mel_row": { "tr": "🎼 Kule melodisi", "en": "🎼 Tower melody" },
	"alb_row": { "tr": "📖 Albüm", "en": "📖 Album" },
	"cam_row": { "tr": "📷 Kartpostal", "en": "📷 Postcard" },
	"p_sound": { "tr": "SES ATMOSFERİ  (tamamı sentez, telifsiz)", "en": "SOUND ATMOSPHERE  (fully synthesized)" },
	"p_melody": { "tr": "KULE MELODİN", "en": "YOUR TOWER MELODY" },
	"p_mail": { "tr": "MEKTUPLAR", "en": "LETTERS" },
	"p_stats": { "tr": "EMEĞİN", "en": "YOUR EFFORT" },
	"p_album": { "tr": "ALBÜM", "en": "ALBUM" },
	"p_town": { "tr": "KASABA", "en": "TOWN" },
	"reply": { "tr": "İçtenlikle yanıtla", "en": "Reply warmly" },
	"replied": { "tr": "✓ yanıtladın · bağ +1", "en": "✓ replied · bond +1" },
	"tt_focus": { "tr": "Odak seansı: sen çalışırken kasaba ×1.5 büyür", "en": "Focus session: your town grows ×1.5 while you work" },
	"tt_series": { "tr": "Bugünkü seri · emek istatistikleri", "en": "Today's streak · effort stats" },
	"tt_town": { "tr": "Ses · Melodi · Albüm · Kartpostal", "en": "Sound · Melody · Album · Postcard" },
	"tt_mute": { "tr": "Sesi sustur / aç", "en": "Mute / unmute" },
	"tt_mail": { "tr": "Sakinlerden gelen mektuplar", "en": "Letters from your residents" },
	"tt_close": { "tr": "Kapat (Esc)", "en": "Close (Esc)" },
	"date_fmt": { "tr": "%d. yıl · gün %d", "en": "year %d · day %d" },
	"tier0": { "tr": "Mezra", "en": "Hamlet" },
	"tier1": { "tr": "Köy", "en": "Village" },
	"tier2": { "tr": "Büyük Köy", "en": "Large Village" },
	"tier3": { "tr": "Kasaba", "en": "Town" },
	"tier4": { "tr": "Küçük Şehir", "en": "Small City" },
	"tier5": { "tr": "Şehir", "en": "City" },
	"season0": { "tr": "ilkbahar", "en": "spring" },
	"season1": { "tr": "yaz", "en": "summer" },
	"season2": { "tr": "sonbahar", "en": "autumn" },
	"season3": { "tr": "kış", "en": "winter" },
	"mode0": { "tr": "Pomodoro 25/5", "en": "Pomodoro 25/5" },
	"mode1": { "tr": "Derin 50/10", "en": "Deep Work 50/10" },
	# ---- sakin evreleri + hover kartı ----
	"stage0": { "tr": "🌱 çocuk", "en": "🌱 child" },
	"stage1": { "tr": "yetişkin", "en": "adult" },
	"stage2": { "tr": "🕰 bilge", "en": "🕰 elder" },
	"pc_scarf": { "tr": "💛 atkılı", "en": "💛 wears your scarf" },
	"pc_wants_home": { "tr": "🌿 yuva arıyor", "en": "🌿 looking for a home" },
	# ---- HUD / bar ----
	"stat_fmt": { "tr": "ev %d · sakin %d", "en": "homes %d · folk %d" },
	"boot_sub": { "tr": "kasaba uyanıyor", "en": "the town is waking" },
	"boot_events": { "tr": "Kasaba yaşıyor…", "en": "The town lives on…" },
	"wish_short": { "tr": "💭 dilek", "en": "💭 wish" },
	"stats_body": { "tr": "bugün %d dk · toplam %d dk\nseri %d · en uzun seri %d · %d seans",
		"en": "today %d min · total %d min\nstreak %d · best streak %d · %d sessions" },
	# ---- offline özet kartı ----
	"offline_title": { "tr": "SEN YOKKEN", "en": "WHILE YOU WERE AWAY" },
	"offline_body": { "tr": "%.1f gün geçti.\n🌱 %d doğum    ✦ %d veda    🧳 %d yeni komşu\nNüfus %d → %d",
		"en": "%.1f days passed.\n🌱 %d births    ✦ %d farewells    🧳 %d new neighbors\nPopulation %d → %d" },
	"offline_capped": { "tr": "\n(kasaba uzunca kendi halinde yaşadı)", "en": "\n(the town lived on its own for a good while)" },
	"offline_ok": { "tr": "kasabaya dön", "en": "back to town" },
	# ---- melodi paneli ----
	"mel_play": { "tr": "▶ dinle", "en": "▶ listen" },
	"mel_teach": { "tr": "🗼 kuleye öğret", "en": "🗼 teach the tower" },
	"mel_note": { "tr": "Kule her saat başı senin melodini çalar. Sütuna dokun: nota koy/kaldır.",
		"en": "The tower plays your melody every hour. Tap a column to place or remove a note." },
	"mel_concert": { "tr": "Kule melodini öğrendi — MEYDAN KONSERİ! Herkes senin şarkınla dans etti.",
		"en": "The tower learned your melody — TOWN SQUARE CONCERT! Everyone danced to your song." },
	"mel_learned": { "tr": "Kule melodini öğrendi — her saat başı çalacak.",
		"en": "The tower learned your melody — it will play every hour." },
	"mel_hint": { "tr": "Kule öğrendi. İpucu: en az 5 nota, 3 farklı ses ve iniş-çıkış olursa kasaba coşar…",
		"en": "The tower learned it. A tip: with at least 5 notes, 3 different pitches and some rise and fall, the town will cheer…" },
	# ---- albüm ----
	"alb_residents": { "tr": "SAKİNLER (%d)", "en": "RESIDENTS (%d)" },
	"alb_trees": { "tr": "ANI AĞAÇLARI (%d)", "en": "MEMORY TREES (%d)" },
	"alb_tree_fmt": { "tr": "✦ %s'nin ağacı", "en": "✦ %s's tree" },
	"alb_story": { "tr": "KASABANIN HİKÂYESİ", "en": "THE TOWN'S STORY" },
	"alb_story_body": { "tr": "🌱 %d doğum · ✦ %d veda · 🧳 %d gelen\n🌟 %d dilek gerçekleşti · 💛 bağ %d\n🎯 %d seans · %d dk emek · en uzun seri %d",
		"en": "🌱 %d births · ✦ %d farewells · 🧳 %d arrivals\n🌟 %d wishes granted · 💛 bond %d\n🎯 %d sessions · %d min of effort · best streak %d" },
	"alb_concert": { "tr": "🎻 Meydan Konseri verildi", "en": "🎻 A Town Square Concert was held" },
	"alb_atolye": { "tr": "🔨 Atölye kuruldu", "en": "🔨 The Workshop was built" },
	"alb_kutuphane": { "tr": "📚 Kütüphane yükseldi", "en": "📚 The Library rose" },
	# ---- ses mikseri satırları ----
	"snd_music": { "tr": "🎵 müzik", "en": "🎵 music" },
	"snd_rain": { "tr": "🌧 yağmur", "en": "🌧 rain" },
	"snd_stream": { "tr": "💧 dere", "en": "💧 stream" },
	"snd_pad": { "tr": "🎹 lo-fi pad", "en": "🎹 lo-fi pad" },
	"snd_cricket": { "tr": "🦗 gece", "en": "🦗 night" },
	"snd_master": { "tr": "🔊 ana", "en": "🔊 master" },
	# ---- durum cümleleri (world.status_text) ----
	"st_insaat": { "tr": "yeni bir ev yükseliyor…", "en": "a new house is rising…" },
	"st_tasinma": { "tr": "biri taşınıyor…", "en": "someone is moving in…" },
	"st_isil": { "tr": "kasaba ışıl ışıl", "en": "the town is aglow" },
	"st_aksam": { "tr": "akşam çöküyor, ışıklar yanıyor", "en": "evening settles in, lights coming on" },
	"st_aksamustu": { "tr": "huzurlu bir akşamüstü", "en": "a peaceful late afternoon" },
	"st_gun": { "tr": "huzurlu bir gün", "en": "a peaceful day" },
	# ---- dilek metinleri (WISH_TYPES anahtarları sim durumu — TR anahtar, iki dilde görünüm) ----
	"wish_fmt": { "tr": "💭 %s: \"keşke %s olsa\" — dokun, gerçekleştir", "en": "💭 %s: \"I wish there were %s\" — tap to make it real" },
	"wtxt_çeşme": { "tr": "meydana küçük bir çeşme", "en": "a little fountain in the square" },
	"wtxt_ağaç": { "tr": "sokağıma bir ağaç", "en": "a tree on my street" },
	"wtxt_fener": { "tr": "kapımın önüne bir fener", "en": "a lantern by my door" },
	"wtxt_bank": { "tr": "ağacın altına bir bank", "en": "a bench under the tree" },
	"wtxt_kuş yuvası": { "tr": "bahçeme bir kuş yuvası", "en": "a birdhouse in my garden" },
	"wtxt_posta kutusu": { "tr": "kapıma bir posta kutusu", "en": "a mailbox at my door" },
	"wtxt_rüzgâr gülü": { "tr": "çatıma bir rüzgâr gülü", "en": "a weathervane on my roof" },
	"kind_çeşme": { "tr": "çeşme", "en": "fountain" },
	"kind_ağaç": { "tr": "ağaç", "en": "tree" },
	"kind_fener": { "tr": "fener", "en": "lantern" },
	"kind_bank": { "tr": "bank", "en": "bench" },
	"kind_kuş yuvası": { "tr": "kuş yuvası", "en": "birdhouse" },
	"kind_posta kutusu": { "tr": "posta kutusu", "en": "mailbox" },
	"kind_rüzgâr gülü": { "tr": "rüzgâr gülü", "en": "weathervane" },
	# ---- mektup gönderenleri (mektup üretim anındaki dilde save'e girer — bilinçli) ----
	"from_kasaba": { "tr": "Kasaba halkı", "en": "The townsfolk" },
	"from_tuccar": { "tr": "Gezgin tüccar", "en": "A traveling merchant" },
	"from_cift": { "tr": "Yeni evli çift", "en": "The newlyweds" },
	"from_aile": { "tr": "Uzaktan bir aile", "en": "A family from afar" },
	"from_toplayici": { "tr": "Işık Toplayıcısı", "en": "The Light Collector" },
	"from_muzisyen": { "tr": "Gezgin Müzisyen", "en": "The Wandering Musician" },
	# ---- olay akışı (world._push_event) ----
	"ev_dilek": { "tr": "💭 %s bir dilek tuttu", "en": "💭 %s made a wish" },
	"ev_fest0": { "tr": "🌸 Çiçek Günü — meydan taçyaprağı içinde", "en": "🌸 Flower Day — the square is deep in petals" },
	"ev_fest1": { "tr": "💧 Dere Şenliği — kâğıt kayıklar yarışıyor", "en": "💧 Stream Festival — paper boats are racing" },
	"ev_fest2": { "tr": "🎃 Hasat Akşamı — meydanda uzun sofra kuruldu", "en": "🎃 Harvest Evening — a long table set in the square" },
	"ev_fest3": { "tr": "🏮 Fener Gecesi — ışıklar karda süzülüyor", "en": "🏮 Lantern Night — lights drifting through the snow" },
	"ev_yagmur": { "tr": "🌧 kasabaya yağmur geldi", "en": "🌧 rain has come to town" },
	"ev_yagmur_dindi": { "tr": "🌦 yağmur dindi — toprak kokusu", "en": "🌦 the rain has passed — the smell of wet earth" },
	"ev_kulube_ev": { "tr": "🏠 bir kulübe sıcacık bir eve dönüştü", "en": "🏠 a hut grew into a warm little home" },
	"ev_tas_ev": { "tr": "🏛 bir ev taş eve yükseldi — mahalle gururla bakıyor", "en": "🏛 a home rose into a stone house — the whole street beams with pride" },
	"ev_tier": { "tr": "🪧 tabela yenilendi — artık bir %s'yiz! Meydanda kutlama var", "en": "🪧 the sign was repainted — we're a %s now! There's a celebration in the square" },
	"ev_gun30": { "tr": "🕯 kasabanın 30. günü — meydanda mum ışığı", "en": "🕯 the town's 30th day — candlelight in the square" },
	"ev_sakin100": { "tr": "💯 100. komşu aramızda", "en": "💯 our 100th neighbor is here" },
	"ev_veda50": { "tr": "🌳 50. anı ağacı — çayır artık bir koru", "en": "🌳 the 50th memory tree — the meadow is a grove now" },
	"ev_kuyu": { "tr": "⛲ mahalleye bir KUYU kazılıyor", "en": "⛲ a WELL is being dug for the neighborhood" },
	"ev_firin": { "tr": "🍞 kasabaya FIRIN yapılıyor — sabahlar ekmek kokacak", "en": "🍞 a BAKERY is being built — mornings will smell of fresh bread" },
	"ev_pazar": { "tr": "🧺 meydana PAZAR tezgâhı kuruluyor", "en": "🧺 MARKET stalls are going up in the square" },
	"ev_cayevi": { "tr": "🍵 köşeye ÇAYEVİ açılıyor — akşam sohbetleri burada", "en": "🍵 a TEAHOUSE is opening on the corner — evening chats live here now" },
	"ev_okul": { "tr": "🏫 çocuklar için OKUL yükseliyor", "en": "🏫 a SCHOOL is rising for the children" },
	"ev_degirmen": { "tr": "🌾 dere kenarına DEĞİRMEN kuruluyor", "en": "🌾 a MILL is being built by the stream" },
	"ev_han": { "tr": "🏮 gezginler için HAN yapılıyor", "en": "🏮 an INN is being built for travelers" },
	"ev_festival_alani": { "tr": "🎪 FESTİVAL ALANI hazırlanıyor — bayraklar asıldı", "en": "🎪 the FESTIVAL GROUNDS are being readied — the flags are up" },
	"ev_butunlendi": { "tr": "🎊 KASABA BÜTÜNLENDİ — son ev de yuvasını buldu", "en": "🎊 THE TOWN IS WHOLE — the last house found its family" },
	"ev_densify": { "tr": "🏘 kasaba içe doğru sıklaşıyor — yeni sokaklar açıldı", "en": "🏘 the town is growing inward — new streets have opened" },
	"ev_cicek": { "tr": "🌸 bir evin pencereleri çiçeklendi", "en": "🌸 a house's windows burst into bloom" },
	"ev_senlik": { "tr": "🎪 meydanda küçük bir şenlik kuruldu", "en": "🎪 a little festivity sprang up in the square" },
	"ev_buyudu": { "tr": "🌿 %s büyüdü, kendine yuva arıyor", "en": "🌿 %s has grown up and is looking for a home" },
	"ev_bilge": { "tr": "🕰 %s artık kasabanın bilgesi", "en": "🕰 %s is one of the town's elders now" },
	"ev_cift": { "tr": "💍 %s ve %s birlikte yuva kurdu", "en": "💍 %s and %s made a home together" },
	"ev_tek_yuva": { "tr": "🏡 %s kendi yuvasına taşındı", "en": "🏡 %s moved into a home of their own" },
	"ev_soz_aile": { "tr": "🧳 mektuptaki aile geldi — kapıda sıcak çorba bekliyordu", "en": "🧳 the family from the letter arrived — warm soup was waiting at the door" },
	"ev_yeni_aile": { "tr": "🧳 uzaktan yeni bir aile geldi", "en": "🧳 a new family arrived from afar" },
	"ev_dogum": { "tr": "🌱 %s dünyaya geldi", "en": "🌱 %s was born" },
	"ev_isik_sondu": { "tr": "🌒 bir evin ışıkları söndü", "en": "🌒 a house's lights went dark" },
	"ev_veda": { "tr": "✦ %s yıldızlara karıştı — çayıra bir anı ağacı dikildi", "en": "✦ %s joined the stars — a memory tree was planted in the meadow" },
	"ev_melodi": { "tr": "🎼 kule yeni melodini öğrendi", "en": "🎼 the tower learned your new melody" },
	"ev_konser": { "tr": "🎻 MEYDAN KONSERİ! Gezgin Müzisyen kasabaya yerleşti", "en": "🎻 TOWN SQUARE CONCERT! The Wandering Musician has settled here" },
	"ev_melodi_ipucu": { "tr": "🎼 kule öğrendi — ipucu: ≥5 nota, ≥3 farklı ses, iniş-çıkış", "en": "🎼 the tower learned it — tip: ≥5 notes, ≥3 pitches, some rise and fall" },
	"ev_seans_insaat": { "tr": "🔨 seansının şerefine yeni bir yapı yükseliyor", "en": "🔨 a new building rises in honor of your session" },
	"ev_seans_terfi": { "tr": "🏠 emeğinle bir ev güzelleşti", "en": "🏠 your effort made a home lovelier" },
	"ev_atolye": { "tr": "🔨 seri ödülü: Atölye kuruluyor", "en": "🔨 streak reward: a Workshop is being built" },
	"ev_kutuphane": { "tr": "📚 seri ödülü: Kütüphane yükseliyor", "en": "📚 streak reward: a Library is rising" },
	"ev_rasathane": { "tr": "🔭 Rasathane yükseliyor — gökyüzü artık daha yakın", "en": "🔭 an Observatory is rising — the sky feels closer now" },
	"ev_sera": { "tr": "🌿 Sera kuruluyor — kışın bile yeşil", "en": "🌿 a Greenhouse is going up — green even in winter" },
	"ev_hamam": { "tr": "♨ Hamam yükseliyor — yorgunluğa veda", "en": "♨ a Bathhouse is rising — farewell to weariness" },
	"ev_ses50": { "tr": "🗿 50. seans — meydana minik bir heykel dikildi", "en": "🗿 50th session — a little statue now stands in the square" },
	"ev_ses75": { "tr": "⛩ 75. seans — çayıra bir kameriye kuruldu", "en": "⛩ 75th session — a pergola was raised in the meadow" },
	"ev_ses100": { "tr": "🌳 100. seans — Yüzyıl Meşesi dikildi", "en": "🌳 100th session — the Century Oak was planted" },
	"ev_ses150": { "tr": "🏮 150. seans — meydana fener dizisi asıldı", "en": "🏮 150th session — a string of lanterns hung around the square" },
	"ev_ses200": { "tr": "✨ 200. seans — kulenin kenarları yaldızlandı", "en": "✨ 200th session — the tower's edges were gilded" },
	"ev_ses300": { "tr": "🌷 300. seans — Zafer Bahçesi açıldı", "en": "🌷 300th session — the Victory Garden opened" },
	"ev_ses500": { "tr": "🔥 500. seans — meydanda Ebedi Alev yakıldı", "en": "🔥 500th session — the Eternal Flame was lit in the square" },
	"ev_seans_bitti": { "tr": "🎉 odak seansı tamamlandı — kasaba kutluyor", "en": "🎉 focus session complete — the town celebrates" },
	"ev_tuccar": { "tr": "🐴 gezgin tüccar uğradı — meydana bir %s hediye bıraktı", "en": "🐴 a traveling merchant passed through — left a %s in the square as a gift" },
	"ev_dugun": { "tr": "💒 bugün düğün var — %s ve %s yeni yuvalarına taşınıyor", "en": "💒 there's a wedding today — %s and %s are moving into their new home" },
	"ev_hasat": { "tr": "🌾 hasat şenliği — meydanda uzun sofra, herkes davetli", "en": "🌾 harvest festival — a long table in the square, everyone's invited" },
	"ev_gokkusagi": { "tr": "🌈 yağmurun ardından gökkuşağı çıktı — herkes başını kaldırdı", "en": "🌈 a rainbow after the rain — everyone looked up" },
	"ev_balon": { "tr": "🎈 gökyüzünden bir balon geçiyor — çocuklar el sallıyor", "en": "🎈 a balloon drifts across the sky — the children are waving" },
	"ev_gocebe": { "tr": "📮 uzaktan bir mektup: 'yarın geliyoruz' — bir aile katılmak istiyor", "en": "📮 a letter from afar: 'we arrive tomorrow' — a family wants to join us" },
	"ev_kus": { "tr": "🕊 bir kuş sürüsü kasabanın üstünden geçti — kule bir kez selam çaldı", "en": "🕊 a flock of birds passed over town — the tower rang once in greeting" },
	"ev_ucurtma": { "tr": "🪁 uçurtma günü — çocuklar çayırda, gökyüzü rengârenk", "en": "🪁 kite day — children in the meadow, the sky full of color" },
	"ev_yildiz": { "tr": "🌠 gece yıldız yağmuru — herkes bir dilek tuttu", "en": "🌠 a meteor shower tonight — everyone made a wish" },
	"ev_ziyaretci": { "tr": "🏮 nadir bir konuk: Işık Toplayıcısı melodini dinlemeye geldi", "en": "🏮 a rare guest: the Light Collector came to hear your melody" },
	"ev_dilek_gercek": { "tr": "🌟 %s'nın dileği gerçek oldu", "en": "🌟 %s's wish came true" },
	"ev_yanit": { "tr": "💛 %s yanıtını aldı", "en": "💛 %s received your reply" },
	"ev_kartpostal": { "tr": "📷 kartpostal kaydedildi (Resimler klasörü)", "en": "📷 postcard saved (Pictures folder)" },
	"ev_kartpostal_fail": { "tr": "📷 kartpostal kaydedilemedi", "en": "📷 couldn't save the postcard" },
}
